baseURL = "https://wirthy21.github.io/"
locale = "en-us"
title = "Jannik Wirtheim"
disableKinds = ["RSS"]

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[author]
  name = "Jannik Wirtheim"
  email = "jannik.wirtheim@gmx.de"

[params]
  sitename = "Jannik Wirtheim"
  defaultColor = "dark"
  description = "Personal website of Jannik Wirtheim"

[params.author]
  avatar = "Bewerbungsfoto.jpg"
  intro = "Jannik Wirtheim"
  name = "Jannik Wirtheim"
  description = "Data Science & Machine Learning"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/wirthy21"

[[params.socialIcons]]
  name = "email"
  url = "mailto:jannik.wirtheim@gmx.de"

[[params.socialIcons]]
  name = "kaggle"
  url = "https://www.kaggle.com/wirthy"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jannik-wirtheim-880490231/"

[[menu.main]]
  pageRef = "video"
  name = "Video"
  url = "/video/"
  weight = 10

[[menu.main]]
  pageRef = "experience"
  name = "Experiences"
  url = "/experience/"
  weight = 20

[[menu.main]]
  pageRef = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 30

[[menu.main]]
  pageRef = "publications"
  name = "Publications"
  url = "/publications/"
  weight = 40

[[menu.main]]
  pageRef = "skills"
  name = "Skills"
  url = "/skills/"
  weight = 50

[[menu.main]]
  pageRef = "personal"
  name = "Personal"
  url = "/personal/"
  weight = 60

[[menu.main]]
  pageRef = "cv"
  name = "CV"
  url = "/cv/"
  weight = 70

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true